# Generated by Django 4.1.5 on 2023-09-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Release_Date',
            field=models.DateField(auto_now=True, help_text='Format: YYYY-MM-DD', verbose_name='Release_Date'),
        ),
    ]
