# Generated by Django 4.1.5 on 2023-09-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_movie1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie1',
            new_name='Movie2',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
